sortString_1
ostapenko-me/frontend-homework pull request #36
Opened 2017-02-10 10:36 UTC by IVyazmin

Вязьмин Илья

2017-02-10 17:56 UTC, IlyaNikk commented on source/sortString.js
> +	var words = string.split(" ");
Замени везде var на let, почитай здесь почему лучше именно let использовать https://learn.javascript.ru/let-const

2017-02-10 17:56 UTC, IlyaNikk commented on source/sortString.js
> +		chars = chars.sort(function (a, b) {
Лучше замени на стрелочные функции https://learn.javascript.ru/es-function

2017-02-10 17:57 UTC, IlyaNikk reviewed
Привет. Я тебе пару комментариев оставил по коду, поправь их и норм будет

2017-02-19 07:59 UTC, KOPTE3 commented
# Привет

Чтобы задание было зачтено, тебе необходимо исправить все замечания. Советую не затягивать с этим. После __26 февраля__ баллы за эту задачу будут срезаны. Чтобы получить 5 баллов, необходимо будет решить более сложную задачу.

2017-02-19 19:03 UTC, IVyazmin commented
Вязьмин Илья 11вариант

2017-02-20 20:30 UTC, avtyul requested changes
Привет, ты уже близок к успеху. Подъехали еще замечания. Жду изменений!

2017-02-20 20:30 UTC, avtyul commented on index.html
> +    <script src="source/sortString.js"></script>
отступы поехали

2017-02-20 20:30 UTC, avtyul commented on source/sortString.js
> +		words[i] = chars.join("");
можно было сделать цепочку вызовов в одну строчку

2017-02-20 20:30 UTC, avtyul commented on source/sortString.js
> +	return string;
```javascript
return words.sort((a, b) => a.localeCompare(b)).join('') 
```

2017-02-20 20:30 UTC, avtyul commented on source/sortString.js
> +}
git ждет newline

2017-02-20 20:31 UTC, avtyul commented
По условию задачи необходимо дописать свои тесты.

2017-02-21 16:34 UTC, avtyul commented on index.html
> +	<script src="https://code.jquery.com/qunit/qunit-2.1.1.js"></script>s
`>s`

2017-02-21 16:34 UTC, avtyul commented on index.html
> +    <script src="source/sortString.js"></script>
все еще уехало влево

2017-02-21 16:36 UTC, avtyul commented on source/sortString.js
> +	return string.split(" ").map( (item, i, arr) => item.split("").sort( (a, b) => a.localeCompare(b) ).join("") ).sort( (a, b) => a.localeCompare(b) ).join(" ");
В JS любят одинарные кавычки `'JS'`
если ты не используешь параметры функции map, не обязательно их дописывать

2017-02-21 16:36 UTC, avtyul commented on source/sortString.js
> +}
таки newline нужен

2017-02-21 16:37 UTC, avtyul approved these changes

2017-02-21 16:37 UTC, avtyul commented
В общем, теперь топ!
Следи за отступами и выбирай правильные кавычки.
**5/5 баллов**

2017-02-21 16:37 UTC, closed without merging