Homework 0 done (Govyazin APO-12, VAR 13)
ostapenko-me/frontend-homework pull request #42
Opened 2017-02-10 14:22 UTC by SCaptainCAP

2017-02-10 19:55 UTC, nksoff requested changes
Привет, хорошее решение, но нужно исправить небольшие замечания

2017-02-10 19:55 UTC, nksoff commented on source/tree.js
> +    }
что-то случилось с отступами :-(

2017-02-10 19:55 UTC, nksoff commented on source/tree.js
> +	var answer = '';
в модном, молодежном js стараются не использовать `var`. вместо него - [let и const](https://learn.javascript.ru/let-const)

2017-02-10 19:55 UTC, nksoff commented on source/tree.js
> +const tree = function (height) {
попробуй использовать [стрелочные функции](https://learn.javascript.ru/es-function#функции-через)

2017-02-19 07:58 UTC, KOPTE3 commented
# Привет

Чтобы задание было зачтено, тебе необходимо исправить все замечания. Советую не затягивать с этим. После __26 февраля__ баллы за эту задачу будут срезаны. Чтобы получить 5 баллов, необходимо будет решить более сложную задачу.

2017-02-26 15:09 UTC, nksoff commented
# Круто!

Когда у стрелочной функции один аргумент, можно опустить скобки (`const tree = height => {`)

Зачтено: **5/5 баллов**. На досуге можно порешать [задачки](https://gist.github.com/KOPTE3/3ee6e2cf4c2ae74f6a3c6511debb608a).

2017-02-26 15:09 UTC, closed without merging

2017-02-26 15:31 UTC, SCaptainCAP commented
Спасибо!